version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/validate:
          checkout: true
          path: circleci_terraform
          context: terraform
          requires:
            - terraform/fmt
      - terraform/plan:
          path: circleci_terraform
          checkout: true
          context: terraform
          requires:
            - terraform/validate

