version: 2.1
orbs:
  kubernetes: circleci/kubernetes@1.3.0
  aws-cli: circleci/aws-cli@3.1.1
executors:
  environment:
    docker:
      - image: circleci/python
    working_directory: ~/repo

jobs:
  build:
    executor: environment
    steps:
      - checkout
      - kubernetes/install
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION


workflows:
  version: 2
  build_and_copy:
    jobs:
      - build
