version: 2.1
orbs:
  slack: circleci/slack@4.9.3
executors:
  environment:
    docker:
      - image: cimg/base
    working_directory: ~/repo
jobs:
  build:
    executor: environment
    steps:
      - checkout
      - run: mkdir -p ~/repo/workspace
      - run:
        command: |
          echo $CIRCLE_USERNAME
workflows:
  version: 2
  build_and_copy:
    jobs:
      - build: