version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/validate:
          path: ~./circleci_terraform/
          checkout: true
          context: terraform

      - terraform/plan:
          checkout: true
          context: terraform
          path: ~./circleci_terraform/
