version: 2.1
orbs: 
  terraform: circleci/terraform@3.1.0
jobs:
  notify:
    step: 
      - checkout
      - terraform/fmt:
        checkout: true
        context: terraform 
        path: ~/.circleci_terraform/
      - terraform/validate:
        checkout: true
        context: terraform
workflows:
  deploy_and_notify:
    jobs:
      - notify
