version: 2.1
executors:
  environment:
    docker:
      - image: circleci/node:10.14-browsers
    working_directory: ~/repo

jobs:
  build:
    executor: environment
    steps:
      - checkout
      - run: mkdir -p ~/repo/workspace


workflows:
  version: 2
  build_and_copy:
    jobs:
      - build
