version: '2.1'
orbs:
  terraform: circleci/terraform@3.1
workflows:
  deploy_infrastructure:
    jobs:
      - run: 
          command: pwd
      - terraform/validate:
          checkout: true
          path: circleci_terraform
          context: terraform

      - terraform/plan:
          path: circleci_terraform
          checkout: true
          context: terraform
