version: 2.1
orbs: 
  terraform: circleci/terraform@3.1.0
  slack: circleci/slack@4.10.1
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    step: 
      - checkout
      - terraform/fmt:
        checkout: true
        context: terraform 
      - terraform/validate:
        checkout: true
        context: terraform
      - slack/notify:
        event: pass
        template: success_tagged_deploy_1
workflows:
  deploy_and_notify:
    jobs:
      - notify
