version: '2.1'
orbs:
  terraform: circleci/terraform@3.1.0
workflows:
  deploy_infra:
    jobs:
      - terraform/validate:
          checkout: true
          context: terraform
      - terraform/plan:
          checkout: true
          context: terraform
          persist-workspace: true
          requires:
            - terraform/validate
